/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package RestaurantManagement;

import java.util.*;
import javax.swing.*;
import java.util.*;
import javax.swing.event.*;



/**
 *
 * @author ahmetgultekin
 */
public class OrderForm extends javax.swing.JFrame {    
    int mainDishesPrice = 10;
    int saladPrice = 5;
    int waterPrice = 1;
    int colaPrice = 2;
    int spritePrice = 2;
    int hessEstatePrice = 15;
    int catenaMalbecPrice = 10;
    int montereyPinotPrice = 15;
    JLabel[] amountLabels;
    JSpinner[] spinnersArray;
    static double totalAmount = 0;
    
    
    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        this.amountLabels = new JLabel[]{jLabelVindalooAmount, jLabelArrozAmount, jLabelSardinhasAmount, jLabelGardenSaladAmount, jLabelBltSaladAmount, jLabelCaesarSaladAmount, jLabelWaterAmount, jLabelColaAmount, jLabelSpriteAmount, jLabelHessEstateAmount, jLabelCatenaMalbecAmount, jLabelMontereyPinotAmount };
        this.spinnersArray = new JSpinner[] {jSpinnerVindaloo, jSpinnerArroz, jSpinnerSardinhas, jSpinnerGardenSalad, jSpinnerBltSalad, jSpinnerCaesarSalad, jSpinnerWater, jSpinnerCola, jSpinnerSprite, jSpinnerHessEstate, jSpinnerCatenaMalbec, jSpinnerMontereyPinot };
        initComponents();
    }

    // This method set all meals amount label according to price and quantity (it is created to ease of use and less code)
    private void setAmountLabelFromSpinner(javax.swing.JSpinner spinner, javax.swing.JLabel amountLabel, double price) {
        int objectAmount = (Integer) spinner.getValue();
        double endAmount = objectAmount * price;
        amountLabel.setText(String.valueOf(endAmount));
        // This totalAmount variable sets its value when this function calls, and when you press the complete order button it's appear on the total amount label.
        totalAmount += endAmount;
    }
    
    
    // This method convert all Amount Labels to empty string
    private void cleanLabels(javax.swing.JLabel... labels) {
       
        for(javax.swing.JLabel label: labels) {
            try {
                label.setText("0");
            }
            catch(NullPointerException e) {
                System.out.println("NullPointerException thrown!");
            }
        }
    }
    
    // This method convert all spinners to zero(0)
    private void cleanSpinners(javax.swing.JSpinner... spinners) {
        
        for(javax.swing.JSpinner spinner: spinners) {
            try {
                spinner.setValue(0);
            }
            catch(NullPointerException e) {
                System.out.println("NullPointerException thrown!");
            }
        }
        
        totalAmount = 0;
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelWelcome = new javax.swing.JLabel();
        jLabelChooseYourOrder = new javax.swing.JLabel();
        jPanelSalads = new javax.swing.JPanel();
        jLabelQuantitySalads = new javax.swing.JLabel();
        jLabelAmountSalads = new javax.swing.JLabel();
        jSpinnerGardenSalad = new javax.swing.JSpinner();
        jSpinnerBltSalad = new javax.swing.JSpinner();
        jSpinnerCaesarSalad = new javax.swing.JSpinner();
        jLabelGardenSaladAmount = new javax.swing.JLabel();
        jLabelBltSaladAmount = new javax.swing.JLabel();
        jLabelCaesarSaladAmount = new javax.swing.JLabel();
        jLabelGardenSalad = new javax.swing.JLabel();
        jLabelBltSalad = new javax.swing.JLabel();
        jLabelCaesarSalad = new javax.swing.JLabel();
        jPanelMainDishes = new javax.swing.JPanel();
        jLabelQuantityMainDishes = new javax.swing.JLabel();
        jLabelAmountMainDishes = new javax.swing.JLabel();
        jLabelVindalooAmount = new javax.swing.JLabel();
        jLabelArrozAmount = new javax.swing.JLabel();
        jLabelSardinhasAmount = new javax.swing.JLabel();
        jSpinnerVindaloo = new javax.swing.JSpinner();
        jSpinnerArroz = new javax.swing.JSpinner();
        jSpinnerSardinhas = new javax.swing.JSpinner();
        jLabelVindaloo = new javax.swing.JLabel();
        jLabelArrozDePato = new javax.swing.JLabel();
        jLabelSardinhas = new javax.swing.JLabel();
        jPanelDrinks = new javax.swing.JPanel();
        jLabelQuantityDrinks = new javax.swing.JLabel();
        jLabelAmountDrinks = new javax.swing.JLabel();
        jSpinnerWater = new javax.swing.JSpinner();
        jSpinnerCola = new javax.swing.JSpinner();
        jSpinnerSprite = new javax.swing.JSpinner();
        jLabelWaterAmount = new javax.swing.JLabel();
        jLabelColaAmount = new javax.swing.JLabel();
        jLabelSpriteAmount = new javax.swing.JLabel();
        jLabelWater = new javax.swing.JLabel();
        jLabelCola = new javax.swing.JLabel();
        jLabelSprite = new javax.swing.JLabel();
        jPanelWines = new javax.swing.JPanel();
        jLabelQuantityWines = new javax.swing.JLabel();
        jLabelAmountWines = new javax.swing.JLabel();
        jSpinnerHessEstate = new javax.swing.JSpinner();
        jSpinnerCatenaMalbec = new javax.swing.JSpinner();
        jSpinnerMontereyPinot = new javax.swing.JSpinner();
        jLabelHessEstateAmount = new javax.swing.JLabel();
        jLabelCatenaMalbecAmount = new javax.swing.JLabel();
        jLabelMontereyPinotAmount = new javax.swing.JLabel();
        jLabelHessEstate = new javax.swing.JLabel();
        jLabelCatenaMalbec = new javax.swing.JLabel();
        jLabelMontereyPinot = new javax.swing.JLabel();
        jButtonEnterOrder = new javax.swing.JButton();
        jComboBoxTablesNo = new javax.swing.JComboBox<>();
        jLabelTableName = new javax.swing.JLabel();
        jButtonCompleteOrder = new javax.swing.JButton();
        jButtonCalculateBill = new javax.swing.JButton();
        jLabelTotalAmount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1150, 1150));
        setMinimumSize(new java.awt.Dimension(1065, 870));
        setName("mainOrderFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1150, 950));

        jLabelWelcome.setFont(new java.awt.Font("Kokonor", 0, 48)); // NOI18N
        jLabelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWelcome.setText("Welcome to Ahmet's Place");
        jLabelWelcome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));

        jLabelChooseYourOrder.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        jLabelChooseYourOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChooseYourOrder.setText("Choose Your Order");

        jPanelSalads.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)), "Salads", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabelQuantitySalads.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelQuantitySalads.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantitySalads.setText("Quantity");

        jLabelAmountSalads.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelAmountSalads.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmountSalads.setText("Amount");

        jSpinnerGardenSalad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerGardenSalad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerGardenSaladStateChanged(evt);
            }
        });

        jSpinnerBltSalad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerBltSalad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerBltSaladStateChanged(evt);
            }
        });

        jSpinnerCaesarSalad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerCaesarSalad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCaesarSaladStateChanged(evt);
            }
        });

        jLabelGardenSaladAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelBltSaladAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelCaesarSaladAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelGardenSalad.setText("Garden Salad");

        jLabelBltSalad.setText("BLT Salad");

        jLabelCaesarSalad.setText("Caesar Salad");

        javax.swing.GroupLayout jPanelSaladsLayout = new javax.swing.GroupLayout(jPanelSalads);
        jPanelSalads.setLayout(jPanelSaladsLayout);
        jPanelSaladsLayout.setHorizontalGroup(
            jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaladsLayout.createSequentialGroup()
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaladsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelGardenSalad)
                            .addComponent(jLabelBltSalad)
                            .addComponent(jLabelCaesarSalad))
                        .addGap(99, 99, 99)
                        .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerBltSalad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerGardenSalad)
                            .addComponent(jSpinnerCaesarSalad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSaladsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelQuantitySalads, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSaladsLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelAmountSalads, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGardenSaladAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBltSaladAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelCaesarSaladAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelSaladsLayout.setVerticalGroup(
            jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaladsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantitySalads)
                    .addComponent(jLabelAmountSalads))
                .addGap(19, 19, 19)
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerGardenSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGardenSaladAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGardenSalad))
                .addGap(42, 42, 42)
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerBltSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBltSaladAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBltSalad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanelSaladsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCaesarSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCaesarSaladAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCaesarSalad))
                .addGap(34, 34, 34))
        );

        jPanelMainDishes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)), "Main Dishes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabelQuantityMainDishes.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelQuantityMainDishes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantityMainDishes.setText("Quantity");

        jLabelAmountMainDishes.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelAmountMainDishes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmountMainDishes.setText("Amount");

        jLabelVindalooAmount.setToolTipText("");
        jLabelVindalooAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelArrozAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelSardinhasAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jSpinnerVindaloo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerVindaloo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerVindalooStateChanged(evt);
            }
        });

        jSpinnerArroz.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerArroz.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerArrozStateChanged(evt);
            }
        });

        jSpinnerSardinhas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerSardinhas.setPreferredSize(new java.awt.Dimension(67, 23));
        jSpinnerSardinhas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSardinhasStateChanged(evt);
            }
        });

        jLabelVindaloo.setText("Vindaloo");

        jLabelArrozDePato.setText("Arroz de Pato");

        jLabelSardinhas.setText("Sardinhas Assadas");

        javax.swing.GroupLayout jPanelMainDishesLayout = new javax.swing.GroupLayout(jPanelMainDishes);
        jPanelMainDishes.setLayout(jPanelMainDishesLayout);
        jPanelMainDishesLayout.setHorizontalGroup(
            jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainDishesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainDishesLayout.createSequentialGroup()
                        .addComponent(jLabelSardinhas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSpinnerSardinhas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainDishesLayout.createSequentialGroup()
                        .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVindaloo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelArrozDePato))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuantityMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSpinnerArroz, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSpinnerVindaloo, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(81, 81, 81)
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelArrozAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSardinhasAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVindalooAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAmountMainDishes, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
        jPanelMainDishesLayout.setVerticalGroup(
            jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainDishesLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantityMainDishes)
                    .addComponent(jLabelAmountMainDishes))
                .addGap(32, 32, 32)
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVindalooAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerVindaloo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVindaloo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelArrozAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerArroz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelArrozDePato))
                .addGap(33, 33, 33)
                .addGroup(jPanelMainDishesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSardinhasAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerSardinhas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSardinhas))
                .addGap(41, 41, 41))
        );

        jPanelDrinks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)), "Drinks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabelQuantityDrinks.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelQuantityDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantityDrinks.setText("Quantity");

        jLabelAmountDrinks.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelAmountDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmountDrinks.setText("Amount");

        jSpinnerWater.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerWater.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerWaterStateChanged(evt);
            }
        });

        jSpinnerCola.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerCola.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerColaStateChanged(evt);
            }
        });

        jSpinnerSprite.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerSprite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerSpriteStateChanged(evt);
            }
        });

        jLabelWaterAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelColaAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelSpriteAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelWater.setText("Water");

        jLabelCola.setText("Cola");

        jLabelSprite.setText("Sprite");

        javax.swing.GroupLayout jPanelDrinksLayout = new javax.swing.GroupLayout(jPanelDrinks);
        jPanelDrinks.setLayout(jPanelDrinksLayout);
        jPanelDrinksLayout.setHorizontalGroup(
            jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDrinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWater, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCola)
                    .addComponent(jLabelSprite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelQuantityDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerCola, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerWater, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerSprite, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(134, 134, 134)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelWaterAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAmountDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpriteAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanelDrinksLayout.setVerticalGroup(
            jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDrinksLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantityDrinks)
                    .addComponent(jLabelAmountDrinks))
                .addGap(18, 18, 18)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWaterAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelWater)))
                .addGap(28, 28, 28)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelColaAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCola))
                .addGap(27, 27, 27)
                .addGroup(jPanelDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerSprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpriteAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSprite))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanelWines.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 51, 51)), "Wines", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 14))); // NOI18N

        jLabelQuantityWines.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelQuantityWines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuantityWines.setText("Quantity");

        jLabelAmountWines.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelAmountWines.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAmountWines.setText("Amount");

        jSpinnerHessEstate.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerHessEstate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerHessEstateStateChanged(evt);
            }
        });

        jSpinnerCatenaMalbec.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerCatenaMalbec.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCatenaMalbecStateChanged(evt);
            }
        });

        jSpinnerMontereyPinot.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerMontereyPinot.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerMontereyPinotStateChanged(evt);
            }
        });

        jLabelHessEstateAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelCatenaMalbecAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelMontereyPinotAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 153, 153)));

        jLabelHessEstate.setText("Hess Estate");

        jLabelCatenaMalbec.setText("Catena Malbec");

        jLabelMontereyPinot.setText("Monterey Pinot Noir");

        javax.swing.GroupLayout jPanelWinesLayout = new javax.swing.GroupLayout(jPanelWines);
        jPanelWines.setLayout(jPanelWinesLayout);
        jPanelWinesLayout.setHorizontalGroup(
            jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelWinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHessEstate)
                    .addComponent(jLabelCatenaMalbec)
                    .addComponent(jLabelMontereyPinot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelQuantityWines, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerHessEstate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerCatenaMalbec, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpinnerMontereyPinot, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(131, 131, 131)
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelAmountWines, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(jLabelHessEstateAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCatenaMalbecAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelMontereyPinotAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanelWinesLayout.setVerticalGroup(
            jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelWinesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantityWines)
                    .addComponent(jLabelAmountWines))
                .addGap(18, 18, 18)
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerHessEstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHessEstateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHessEstate))
                .addGap(27, 27, 27)
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCatenaMalbecAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jSpinnerCatenaMalbec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelCatenaMalbec)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanelWinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerMontereyPinot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMontereyPinotAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMontereyPinot))
                .addGap(28, 28, 28))
        );

        jButtonEnterOrder.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEnterOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jButtonEnterOrder.setText("ENTER NEW ORDER");
        jButtonEnterOrder.setActionCommand("ENTER NEW ORDER");
        jButtonEnterOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnterOrderActionPerformed(evt);
            }
        });

        jComboBoxTablesNo.setBackground(new java.awt.Color(102, 102, 102));
        jComboBoxTablesNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Table1", "Table2", "Table3", "Table4" }));

        jLabelTableName.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabelTableName.setText("Table");

        jButtonCompleteOrder.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCompleteOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButtonCompleteOrder.setText("COMPLETE ORDER");
        jButtonCompleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCompleteOrderActionPerformed(evt);
            }
        });

        jButtonCalculateBill.setBackground(new java.awt.Color(102, 102, 102));
        jButtonCalculateBill.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jButtonCalculateBill.setText("CALCULATE BILL");

        jLabelTotalAmount.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabelTotalAmount.setText("Total Amount:");
        jLabelTotalAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelChooseYourOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMainDishes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSalads, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonCalculateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxTablesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonEnterOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jLabelTableName)
                                .addGap(97, 97, 97))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanelDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jButtonCompleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanelWines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(120, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTableName)
                            .addComponent(jButtonEnterOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTablesNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCalculateBill, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabelWelcome)
                        .addGap(31, 31, 31)
                        .addComponent(jLabelChooseYourOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelMainDishes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSalads, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanelWines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCompleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Main dishes spinner stateChanged methods
    private void jSpinnerVindalooStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerVindalooStateChanged
            setAmountLabelFromSpinner(jSpinnerVindaloo, jLabelVindalooAmount, mainDishesPrice);
    }//GEN-LAST:event_jSpinnerVindalooStateChanged

    private void jSpinnerArrozStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerArrozStateChanged
            setAmountLabelFromSpinner(jSpinnerArroz, jLabelArrozAmount, mainDishesPrice);
    }//GEN-LAST:event_jSpinnerArrozStateChanged

    private void jSpinnerSardinhasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSardinhasStateChanged
            setAmountLabelFromSpinner(jSpinnerSardinhas, jLabelSardinhasAmount, mainDishesPrice);
    }//GEN-LAST:event_jSpinnerSardinhasStateChanged

    
    // Salads spinner stateChanged methods
    private void jSpinnerGardenSaladStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerGardenSaladStateChanged
        setAmountLabelFromSpinner(jSpinnerGardenSalad, jLabelGardenSaladAmount, saladPrice);
    }//GEN-LAST:event_jSpinnerGardenSaladStateChanged

    private void jSpinnerBltSaladStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerBltSaladStateChanged
        setAmountLabelFromSpinner(jSpinnerBltSalad, jLabelBltSaladAmount, saladPrice);
    }//GEN-LAST:event_jSpinnerBltSaladStateChanged

    private void jSpinnerCaesarSaladStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCaesarSaladStateChanged
        setAmountLabelFromSpinner(jSpinnerCaesarSalad, jLabelCaesarSaladAmount, saladPrice);
    }//GEN-LAST:event_jSpinnerCaesarSaladStateChanged

    // Drinks spinner stateChanged methods.
    private void jSpinnerWaterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerWaterStateChanged
        setAmountLabelFromSpinner(jSpinnerWater, jLabelWaterAmount, waterPrice);
    }//GEN-LAST:event_jSpinnerWaterStateChanged

    private void jSpinnerColaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerColaStateChanged
        setAmountLabelFromSpinner(jSpinnerCola, jLabelColaAmount, colaPrice);
    }//GEN-LAST:event_jSpinnerColaStateChanged

    private void jSpinnerSpriteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerSpriteStateChanged
        setAmountLabelFromSpinner(jSpinnerSprite, jLabelSpriteAmount, spritePrice);
    }//GEN-LAST:event_jSpinnerSpriteStateChanged

    // Wines' spinner stateChanged methods.
    private void jSpinnerHessEstateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerHessEstateStateChanged
        setAmountLabelFromSpinner(jSpinnerHessEstate, jLabelHessEstateAmount, hessEstatePrice);
    }//GEN-LAST:event_jSpinnerHessEstateStateChanged

    private void jSpinnerCatenaMalbecStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCatenaMalbecStateChanged
        setAmountLabelFromSpinner(jSpinnerCatenaMalbec, jLabelCatenaMalbecAmount, catenaMalbecPrice);
    }//GEN-LAST:event_jSpinnerCatenaMalbecStateChanged

    private void jSpinnerMontereyPinotStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerMontereyPinotStateChanged
        setAmountLabelFromSpinner(jSpinnerMontereyPinot, jLabelMontereyPinotAmount, montereyPinotPrice);
    }//GEN-LAST:event_jSpinnerMontereyPinotStateChanged

    
    private void jButtonCompleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCompleteOrderActionPerformed
         jLabelTotalAmount.setText("Total Amount: " + String.valueOf(totalAmount));
    }//GEN-LAST:event_jButtonCompleteOrderActionPerformed

    private void jButtonEnterOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnterOrderActionPerformed
        // TODO add your handling code here:
       cleanSpinners(jSpinnerVindaloo, jSpinnerArroz, jSpinnerSardinhas, jSpinnerGardenSalad, jSpinnerBltSalad, jSpinnerCaesarSalad, jSpinnerWater, jSpinnerCola, jSpinnerSprite, jSpinnerHessEstate, jSpinnerCatenaMalbec, jSpinnerMontereyPinot);
    }//GEN-LAST:event_jButtonEnterOrderActionPerformed

    
    private void calculateTotalAmount(javax.swing.JLabel... labels) {
        double totalAmount = 0;
        
        for(javax.swing.JLabel label: labels) {
            String labelValue = label.getText();
            System.out.println(labelValue);
            int labelValueInt = Integer.valueOf(labelValue);
            totalAmount += labelValueInt;
        }
       jLabelTotalAmount.setText("Total Amount: " + totalAmount);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculateBill;
    private javax.swing.JButton jButtonCompleteOrder;
    private javax.swing.JButton jButtonEnterOrder;
    private javax.swing.JComboBox<String> jComboBoxTablesNo;
    private javax.swing.JLabel jLabelAmountDrinks;
    private javax.swing.JLabel jLabelAmountMainDishes;
    private javax.swing.JLabel jLabelAmountSalads;
    private javax.swing.JLabel jLabelAmountWines;
    private javax.swing.JLabel jLabelArrozAmount;
    private javax.swing.JLabel jLabelArrozDePato;
    private javax.swing.JLabel jLabelBltSalad;
    private javax.swing.JLabel jLabelBltSaladAmount;
    private javax.swing.JLabel jLabelCaesarSalad;
    private javax.swing.JLabel jLabelCaesarSaladAmount;
    private javax.swing.JLabel jLabelCatenaMalbec;
    private javax.swing.JLabel jLabelCatenaMalbecAmount;
    private javax.swing.JLabel jLabelChooseYourOrder;
    private javax.swing.JLabel jLabelCola;
    private javax.swing.JLabel jLabelColaAmount;
    private javax.swing.JLabel jLabelGardenSalad;
    private javax.swing.JLabel jLabelGardenSaladAmount;
    private javax.swing.JLabel jLabelHessEstate;
    private javax.swing.JLabel jLabelHessEstateAmount;
    private javax.swing.JLabel jLabelMontereyPinot;
    private javax.swing.JLabel jLabelMontereyPinotAmount;
    private javax.swing.JLabel jLabelQuantityDrinks;
    private javax.swing.JLabel jLabelQuantityMainDishes;
    private javax.swing.JLabel jLabelQuantitySalads;
    private javax.swing.JLabel jLabelQuantityWines;
    private javax.swing.JLabel jLabelSardinhas;
    private javax.swing.JLabel jLabelSardinhasAmount;
    private javax.swing.JLabel jLabelSprite;
    private javax.swing.JLabel jLabelSpriteAmount;
    private javax.swing.JLabel jLabelTableName;
    private javax.swing.JLabel jLabelTotalAmount;
    private javax.swing.JLabel jLabelVindaloo;
    private javax.swing.JLabel jLabelVindalooAmount;
    private javax.swing.JLabel jLabelWater;
    private javax.swing.JLabel jLabelWaterAmount;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelDrinks;
    private javax.swing.JPanel jPanelMainDishes;
    private javax.swing.JPanel jPanelSalads;
    private javax.swing.JPanel jPanelWines;
    private javax.swing.JSpinner jSpinnerArroz;
    private javax.swing.JSpinner jSpinnerBltSalad;
    private javax.swing.JSpinner jSpinnerCaesarSalad;
    private javax.swing.JSpinner jSpinnerCatenaMalbec;
    private javax.swing.JSpinner jSpinnerCola;
    private javax.swing.JSpinner jSpinnerGardenSalad;
    private javax.swing.JSpinner jSpinnerHessEstate;
    private javax.swing.JSpinner jSpinnerMontereyPinot;
    private javax.swing.JSpinner jSpinnerSardinhas;
    private javax.swing.JSpinner jSpinnerSprite;
    private javax.swing.JSpinner jSpinnerVindaloo;
    private javax.swing.JSpinner jSpinnerWater;
    // End of variables declaration//GEN-END:variables

    
    
}


